


export default TYPES = {
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    ERROR_GETTING_CATEGORIES: "ERROR_GETTING_CATEGORIES",
    ADD_NEW_CATOGRY_SUCCESS: "ADD_NEW_CATOGRY_SUCCESS",
    ERROR_ADDING_NEW_CATOGRY: "ERROR_ADDING_NEW_CATOGRY",
    GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
    GET_MOVIES_ERROR: "GET_MOVIES_ERROR",
    ADD_NEW_MOVIE_SUCCESS:"ADD_NEW_MOVIE_SUCCESS",
    ERROR_ADDING_NEW_MOVIE: "ERROR_ADDING_NEW_MOVIE",
    DELETE_MOVIE_SUCCESS: "DELETE_MOVIE_SUCCESS",
    ERROR_DELETING_MOVIE: "ERROR_DELETING_MOVIE"
};


